### PR TITLE
Minimal (but functional) Dockerfile

### PR DESCRIPTION
**Pull request by jonathanperret**
Just as it says on the box. This allows one to run MinecraftChat using:

```bash
$ docker build -t minecraftchat .
$ docker run -d -p 3000:3000 minecraftchat
```

Hope this helps.

### CODE REVIEW

**Comment by AlexKvazos** [comment]
How does docker where the start script is located to run the app?

**Comment by jonathanperret** [comment]
This `Dockerfile` actually works, thanks to the `ONBUILD` instructions in the parent image I used (https://github.com/joyent/docker-node/blob/master/0.12/onbuild/Dockerfile):

```
ONBUILD COPY package.json /usr/src/app/
ONBUILD RUN npm install
ONBUILD COPY . /usr/src/app
```

Those instructions are automatically inserted (https://docs.docker.com/reference/builder/#onbuild) at the top of our `Dockerfile`.

By the way, I created an automated build on https://registry.hub.docker.com/u/jonathanperret/minecraftchat, which means you can now start a server with just:

```
$ docker run -d -p 3000:3000 jonathanperret/minecraftchat
```

**Comment by AlexKvazos** [comment]
Awesome! Thank you so much.

**Comment by jonathanperret** [comment]
You're welcome!

**Pull request merged**
